version: '3.4'

services:
  dotnetapp1:
    image: dotnetapp1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
